---
- name: Instalacion de Java
  hosts: buildAgents
  tasks:
    - name: Actualizar la lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar openjdk-11-jdk
      apt:
        name: openjdk-11-jdk
        state: present